resolver: lts-11.4
packages:
  - gi-cairo-render
  - gi-cairo-connector
extra-deps:
  - gi-gdk-3.0.15
  - gi-gtk-3.0.22
  - gi-pango-1.0.16
  - gi-pangocairo-1.0.16
  - gi-gdkpixbuf-2.0.15 
  - gi-gio-2.0.18
